baseURL = "https://rwxt.org"
title = "rwxt"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
googleAnalytics = "G-T5VYH6J8WD"

[params]
fancyTitle = "Joshua Moreton" # title for frontpage, may include image
copyright = "Josh Moreton"
description = 'Cyber Security leader, board advisor, and mentor.'
description2 = 'Keen photographer, web designer, and runner.'
description3 = 'All-round nerd.'

startbuttonText = "Contact me"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]
inlineCSS = true

[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    isHTML = true
    notAlternative = true
    minify = true

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/clients/'
title = "Recent Clients"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Who I am and what I do'
body = '''Hello and welcome to my landing page! I’m Joshua Moreton, and I wear many hats: Cyber Security Leader, Board Advisor, Mentor, and Small Business Consultant. With a passion for helping entrepreneurs and small business owners build high-quality online presences that drive sales, I bring a wealth of experience to the table.

Outside of my professional life, I am an avid photographer, web designer, and runner, constantly exploring new ways to blend creativity with technology. My journey is defined by a relentless curiosity and a commitment to making a meaningful impact in both the digital and physical security landscapes.

This page is your gateway to understanding who I am and how I can support your goals. Whether you need cyber security expertise, strategic guidance, mentorship, or assistance in enhancing your online presence, I’m here to help. Dive in, connect, and let's explore how we can collaborate to achieve success.'''

[[params.one.icon]]
icon = "fa-gem"
style = "1"
label = "gem"

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "heart"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "code"

[params.two]
enable = true

[[params.two.section]]
img = "/img/R1-03104-0021.webp"
img_alt = "blurry background: white/grey"
title = 'Cybersecurity Leader'
body = 'Primarily I am a cybersecurity architect, helping to advise CEOs, CIOs, and CISOs on how to turn cybersecurity from a cost centre to a driver of high quality outcomes for their businesses.'

[[params.two.section]]
img = "/img/R1-03105-019A.webp"
title = 'Small Business Consultant'
body = "Secondarily, I am a builder. I help entrepreneurs and small business owners build businesses. I build websites, I build brands, and I build business technology for my clients."

[[params.two.section]]
img = "/img/R1-03104-0006.webp"
title = 'Mentor and Advisor'
body = 'Tertiarily (?) I help people navigate their careers. I have had the privilege of being mentored by some of the best in the business. I now try to pay that forward by mentoring others, and advising on boards and in the community.'

[params.three]
enable = false
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-code"
title = "Foo bar"
body = "Augue consectetur sded interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag"
title = "Nothing important"
body = "Auguce consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = false
title = "Arccue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#contact"
text = "Get in touch"
special = true

[[params.cta.link]]
href = "#about"
text = "Learn More"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Send me a message. I'd love to chat."
phone = ""
address = "Edinburgh, Scotland"
email = "josh@rwxt.org"
subject = "New Submission!"
formspree_form_id = "mbjnvjwk"

[params.book]
enable = true
title = "Book time with me"
body = "Put time in our diaries to chat."

[params.social]
twitter = ""
linkedin = "joshua-stuart-moreton"
github = "Josh-moreton"
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"