baseURL = "https://rwxt.org"
title = "rwxt"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = ['spectral', 'reveal-hugo']
googleAnalytics = "G-T5VYH6J8WD"

[params]
fancyTitle = "Joshua Moreton"                                          # title for frontpage, may include image
copyright = "Josh Moreton"
description = 'Cybersecurity leader, web designer, and board advisor.'
description2 = 'Keen photographer, mentor, and runner.'
description3 = 'All-round nerd.'

# startbuttonText = "Looking for web design?"
# startbuttonLink = "/book/"
# body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]
inlineCSS = true

[params.reveal_hugo]
history = true

[params.reveal_hugo.custom_theme_options]
targetPath = "css/bento.css"

# used in content/template-example
[params.reveal_hugo.templates.grey]
background = "#424242"
transition = "convex"
autoslide = "5000"

[params.reveal_hugo.templates.darkgrey]
background = "#3A3E45"
transition = "concave"
autoslide = "5000"

[params.reveal_hugo.templates.cyan]
background = "#53AFA6"
transition = "fade"
autoslide = "5000"

[params.reveal_hugo.templates.orange]
background = "#DF6752"
transition = "zoom"
autoslide = "5000"

[outputFormats]
[outputFormats.HTML]
mediaType = "text/html"
isHTML = true
notAlternative = true
minify = true
[outputFormats.reveal]
mediaType = "text/html"
isHTML = true

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/clients/'
title = "Web Development"

[[params.menu.main]]
url = '/cyber/'
title = "Cybersecurity"

[[params.menu.main]]
url = '/book/'
title = "Book Time With Me"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params.one]
enable = true
title = 'Who I am and what I do'
body = '''<p>Hi! I’m Joshua Moreton, a full time cybersecurity leader and part time web designer.</p>

<p>If you're here for web design, you can find some recent clients and example work using the menu. You can also book a free 30 minute consultation, or just chat to me directly using the chat feature below.</p>

<p>Get in touch or explore the site to find out who I am and how we might be able to work together.</p>'''

[[params.one.icon]]
icon = "fa-gem"
style = "1"
label = "gem"

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "heart"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "code"

[params.two]
enable = true

[[params.two.section]]
img = "/img/IMG_1397.webp"
img_alt = "blurry background: white/grey"
title = 'Cybersecurity Leader'
body = 'Primarily I am a cybersecurity architect, helping to advise CEOs, CIOs, and CISOs on how to turn cybersecurity from a cost centre to a driver of high quality outcomes for their businesses.'

[[params.two.section]]
img = "/img/000091820009.jpeg"
title = 'Web Designer'
body = "Secondarily, I am a builder. I help entrepreneurs and small business owners build businesses. I build websites, I build brands, and I build business technology for my clients."

[[params.two.section]]
img = "/img/000091830029.webp"
title = 'Mentor and Advisor'
body = 'Tertiarily (?) I help people navigate their careers. I have had the privilege of being mentored by some of the best in the business. I now try to pay that forward by mentoring others, and advising on boards and in the community.'

[params.three]
enable = false
title = 'Accumsan mus tortor nunc aliquet'
body = '''Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-code"
title = "Foo bar"
body = "Augue consectetur sded interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag"
title = "Nothing important"
body = "Auguce consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Come speak with me"
body = "If you want to talk about Security Strategy, Web Development, or just want to chat, I'm here to help. Either contact me below, or book some time in my diary for a call"

[[params.cta.link]]
href = "/book"
text = "Book time"
special = true

[[params.cta.link]]
href = "/cyber"
text = "Learn - Cyber"
special = false

[[params.cta.link]]
href = "/clients"
text = "Learn - Webdev"
special = false

[params.contact]
enable = false
title = "Contact"
body = "Send me a message. I'd love to chat."
phone = ""
address = "Edinburgh, Scotland"
email = "josh@rwxt.org"
subject = "New Submission!"
formspree_form_id = "mbjnvjwk"

[params.book]
enable = true
title = "Book time with me"
body = "Put time in our diaries to chat."

[params.social]
twitter = ""
linkedin = "joshua-stuart-moreton"
github = "Josh-moreton"
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"
